In [1]:
import pandas as pd

In [2]:
coffee = pd.read_csv(r"complete-pandas-tutorial\warmup-data\coffee.csv")
coffee.index.name = 'ID'
bios = pd.read_csv(r"complete-pandas-tutorial\data\bios.csv")
bios.index = bios["athlete_id"]
bios = bios.drop("athlete_id",axis=1)
bios_new = bios.copy()

In [5]:
bios_new['Category'] = bios_new['height_cm'].apply(lambda x : 'Short' if x<165 else('Avarage' if x < 185 else 'Tall'))
bios_new

,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date,Category
athlete_id,,,,,,,,,,
1,Jean-François Blanchy,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02,Tall
2,Arnaud Boetsch,1969-04-01,Meulan,Yvelines,FRA,France,183.0,76.0,NaN,Avarage
3,Jean Borotra,1898-08-13,Biarritz,Pyrénées-Atlantiques,FRA,France,183.0,76.0,1994-07-17,Avarage
4,Jacques Brugnon,1895-05-11,Paris VIIIe,Paris,FRA,France,168.0,64.0,1978-03-20,Avarage
5,Albert Canet,1878-04-17,Wandsworth,England,GBR,France,NaN,NaN,1930-07-25,Tall
...,...,...,...,...,...,...,...,...,...,...
149222,Polina Luchnikova,2002-01-30,Serov,Sverdlovsk,RUS,ROC,167.0,61.0,NaN,Avarage
149223,Valeriya Merkusheva,1999-09-20,Moskva (Moscow),Moskva,RUS,ROC,168.0,65.0,NaN,Avarage
149224,Yuliya Smirnova,1998-05-08,Kotlas,Arkhangelsk,RUS,ROC,163.0,55.0,NaN,Short
149225,André Foussard,1899-05-19,Niort,Deux-Sèvres,FRA,France,166.0,NaN,1986-03-18,Avarage
149814,Bill Phillips,1913-07-15,Dulwich Hill,New South Wales,AUS,Australia,NaN,NaN,2003-10-20,Tall